package com.chavis.biz.method;

public class AddressMethod {
	public String addressTrans(String str) {
		switch (str) {
		case "서울":
			return "SO";
		case "경기":
			return "GG";
		case "인천":
			return "IC";
		case "강원":
			return "KW";
		case "대전":
			return "DJ";
		case "세종":
			return "SJ";
		case "충남":
			return "CN";
		case "충북":
			return "CB";
		case "부산":
			return "BS";
		case "울산":
			return "US";
		case "경남":
			return "GN";
		case "경북":
			return "GB";
		case "대구":
			return "DG";
		case "광주":
			return "GJ";
		case "전남":
			return "JN";
		case "전북":
			return "JB";
		case "제주":
			return "JJ";
		case "강남구":
			return "GNG";
		case "강동구":
			return "GDG";
		case "강북구":
			return "GBG";
		case "강서구":
			return "GSG";
		case "관악구":
			return "GAG";
		case "광진구":
			return "GJG";
		case "구로구":
			return "GRG";
		case "금천구":
			return "GCG";
		case "노원구":
			return "NWG";
		case "도봉구":
			return "DBG";
		case "동대문구":
			return "DDMG";
		case "동작구":
			return "DJG";
		case "마포구":
			return "MPG";
		case "서대문구":
			return "SDMG";
		case "서초구":
			return "SCG";
		case "성동구":
			return "SDG";
		case "성북구":
			return "SBG";
		case "송파구":
			return "SPG";
		case "양천구":
			return "YCG";
		case "영등포구":
			return "YDPG";
		case "용산구":
			return "YSG";
		case "은평구":
			return "EPG";
		case "종로구":
			return "JRG";
		case "중구":
			return "JG";
		case "중랑구":
			return "JRG";
		case "가평구":
			return "GPG";
		case "고양시":
			return "GYC";
		case "과천시":
			return "GCC";
		case "광명시":
			return "GMC";
		case "광주시":
			return "GJC";
		case "구리시":
			return "GRC";
		case "군포시":
			return "GPC";
		case "김포시":
			return "GPC";
		case "남양주시":
			return "NYJC";
		case "동두천시":
			return "DDCC";
		case "부천시":
			return "BCC";
		case "성남시":
			return "SNC";
		case "수원시":
			return "SWC";
		case "시흥시":
			return "SHC";
		case "안산시":
			return "ASC";
		case "안성시":
			return "ASUNGC";
		case "안양시":
			return "AYC";
		case "양주시":
			return "YJC";
		case "양평군":
			return "YPG";
		case "여주시":
			return "YJC";
		case "연천군":
			return "YCG";
		case "오산시":
			return "OSC";
		case "용인시":
			return "YIC";
		case "의왕시":
			return "EWC";
		case "의정부시":
			return "EJBC";
		case "이천시":
			return "YCC";
		case "파주시":
			return "PJC";
		case "평택시":
			return "PTC";
		case "포천시":
			return "PCC";
		case "하남시":
			return "HNC";
		case "화성시":
			return "HSC";
		case "강화군":
			return "KHG";
		case "계양구":
			return "KYG";
		case "남동구":
			return "NDG";
		case "동구":
			return "DG";
		case "미주홀구":
			return "MJHG";
		case "부평구":
			return "BPG";
		case "서구":
			return "SG";
		case "연수구":
			return "YSG";
		case "옹진군":
			return "WJG";
		case "강릉시":
			return "GRC";
		case "고성군":
			return "GSG";
		case "동해시":
			return "DHC";
		case "삼척시":
			return "SCC";
		case "속초시":
			return "SCS";
		case "양구군":
			return "YGG";
		case "양양군":
			return "YYG";
		case "영월군":
			return "YWG";
		case "원주시":
			return "WJC";
		case "인제군":
			return "IJG";
		case "정선군":
			return "JSG";
		case "철원군":
			return "CWG";
		case "춘천시":
			return "CCC";
		case "태백시":
			return "TBC";
		case "평창군":
			return "PCG";
		case "홍천군":
			return "HCG";
		case "화천군":
			return "HCG";
		case "횡성군":
			return "HSG";
		case "대덕구":
			return "DDG";
		case "유성구":
			return "YSG";
		case "세종시":
			return "SJC";
		case "계룡시":
			return "KRC";
		case "공주시":
			return "GJC";
		case "금산군":
			return "GSG";
		case "논산시":
			return "NSC";
		case "당진시":
			return "DJC";
		case "보령시":
			return "BRC";
		case "부여군":
			return "BYG";
		case "서산시":
			return "SSC";
		case "서천군":
			return "SCG";
		case "아산시":
			return "ASC";
		case "예산군":
			return "YSG";
		case "천안시":
			return "CAC";
		case "청양군":
			return "CYG";
		case "태안군":
			return "TAG";
		case "홍성군":
			return "HSG";
		case "괴산군":
			return "GSG";
		case "단양군":
			return "DYG";
		case "보은군":
			return "BEG";
		case "영동군":
			return "YDG";
		case "옥천군":
			return "OCG";
		case "음성군":
			return "ESG";
		case "제천시":
			return "JCC";
		case "증평군":
			return "JPG";
		case "진천군":
			return "JCG";
		case "청주시":
			return "CJC";
		case "충주시":
			return "CJC";
		case "금정군":
			return "GJG";
		case "기장군":
			return "GJG";
		case "남구":
			return "NG";
		case "동래구":
			return "DRG";
		case "부산진구":
			return "BSJG";
		case "북구":
			return "BG";
		case "사상구":
			return "SSG";
		case "사하구":
			return "SHG";
		case "수영구":
			return "SYG";
		case "연제구":
			return "YJG";
		case "영도구":
			return "YDG";
		case "해운대구":
			return "HWDG";
		case "울주군":
			return "UJG";
		case "거제시":
			return "GJC";
		case "거창군":
			return "GCG";
		case "김해시":
			return "GHC";
		case "남해군":
			return "NHG";
		case "밀양시":
			return "MYC";
		case "사천시":
			return "SCC";
		case "산천군":
			return "SCG";
		case "양산시":
			return "YSC";
		case "의령군":
			return "URG";
		case "진주시":
			return "JJC";
		case "창녕군":
			return "CNG";
		case "창원시":
			return "CWC";
		case "통영시":
			return "TYC";
		case "하동군":
			return "HDG";
		case "함안군":
			return "HAG";
		case "항양군":
			return "HYG";
		case "합천군":
			return "HCG";
		case "경산시":
			return "GSC";
		case "경주시":
			return "GJC";
		case "고령군":
			return "GRG";
		case "구미시":
			return "GMC";
		case "군위군":
			return "GWG";
		case "김천시":
			return "GCC";
		case "문경시":
			return "MGC";
		case "봉화군":
			return "BHG";
		case "상주시":
			return "SJC";
		case "성주군":
			return "SJG";
		case "안동시":
			return "ADC";
		case "영덕군":
			return "YDG";
		case "영양군":
			return "YYG";
		case "영주시":
			return "YJC";
		case "영천시":
			return "YCC";
		case "예천군":
			return "YCG";
		case "울릉군":
			return "URG";
		case "울진군":
			return "UJG";
		case "의성군":
			return "USG";
		case "청도군":
			return "CDG";
		case "청송군":
			return "CSG";
		case "칠곡군":
			return "CGG";
		case "포항시":
			return "PHC";
		case "달서구":
			return "DSG";
		case "달성군":
			return "DSG";
		case "수성구":
			return "SSG";
		case "광산구":
			return "GSG";
		case "강진군":
			return "GJG";
		case "고흥군":
			return "GHG";
		case "곡성군":
			return "GSG";
		case "광양시":
			return "GYC";
		case "구례군":
			return "GRG";
		case "나주시":
			return "NJC";
		case "담양군":
			return "DYG";
		case "목포시":
			return "MPC";
		case "무안군":
			return "MAG";
		case "보성군":
			return "BSG";
		case "순천시":
			return "SCC";
		case "신안군":
			return "SAG";
		case "여수시":
			return "YSC";
		case "영광군":
			return "YGG";
		case "영암군":
			return "YAG";
		case "완도군":
			return "WDG";
		case "장성군":
			return "JSG";
		case "장흥군":
			return "JHG";
		case "진도군":
			return "JDG";
		case "함평군":
			return "HPG";
		case "해남군":
			return "HNG";
		case "화순군":
			return "HSG";
		case "고창군":
			return "GCG";
		case "군산시":
			return "GSC";
		case "김제시":
			return "GJC";
		case "남원시":
			return "NWC";
		case "무주군":
			return "MJG";
		case "부안군":
			return "BAG";
		case "순찬군":
			return "SCG";
		case "완주군":
			return "WJG";
		case "익산시":
			return "ISC";
		case "임실군":
			return "ISG";
		case "장수군":
			return "JSG";
		case "전주시":
			return "JJC";
		case "정읍시":
			return "JEC";
		case "지안군":
			return "JAG";
		case "서귀포시":
			return "SGPC";
		case "제주시":
			return "JJC";
		default:
			return "";
		}
	}
}
